# Generated by Django 5.0 on 2024-04-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Role',
            new_name='role',
        ),
    ]
