# Generated by Django 5.0 on 2024-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_role_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('audit_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
